"""
Complete Constitution Database Generator
Generates 150+ articles, legal procedures, and landmark judgments
Run this to create the comprehensive constitution_data.json
"""

import json
import os

def create_comprehensive_database():
    data = {
        "articles": [],
        "procedures": [],
        "landmark_cases": [],
        "quick_replies": []
    }
    
    # ==================== PART I: UNION AND TERRITORY ====================
    data["articles"].extend([
        {"number": "1", "title": "Name and territory of the Union", "description": "India, that is Bharat, shall be a Union of States. The territory of India shall comprise: (a) the territories of the States; (b) the Union territories specified in the First Schedule; and (c) such other territories as may be acquired.", "keywords": ["india", "bharat", "union of states", "territory", "name"], "category": "Union and its Territory"},
        {"number": "2", "title": "Admission or establishment of new States", "description": "Parliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit.", "keywords": ["new states", "admission", "establishment", "parliament"], "category": "Union and its Territory"},
        {"number": "3", "title": "Formation of new States and alteration of areas, boundaries or names of existing States", "description": "Parliament may by law: (a) form a new State by separation of territory from any State or by uniting two or more States or parts of States; (b) increase the area of any State; (c) diminish the area of any State; (d) alter the boundaries of any State; (e) alter the name of any State.", "keywords": ["new states", "boundaries", "alteration", "formation", "reorganization"], "category": "Union and its Territory"},
        {"number": "4", "title": "Laws made under articles 2 and 3 to provide for the amendment of the First and the Fourth Schedules", "description": "Any law referred to in article 2 or article 3 shall contain such provisions for the amendment of the First Schedule and the Fourth Schedule as may be necessary to give effect to the provisions of the law.", "keywords": ["schedules", "amendment", "first schedule", "fourth schedule"], "category": "Union and its Territory"},
    ])
    
    # ==================== PART II: CITIZENSHIP ====================
    data["articles"].extend([
        {"number": "5", "title": "Citizenship at the commencement of the Constitution", "description": "At the commencement of this Constitution, every person who has his domicile in the territory of India and: (a) who was born in the territory of India; or (b) either of whose parents was born in the territory of India; or (c) who has been ordinarily resident in the territory of India for not less than five years immediately preceding such commencement, shall be a citizen of India.", "keywords": ["citizenship", "domicile", "commencement", "birth"], "category": "Citizenship"},
        {"number": "6", "title": "Rights of citizenship of certain persons who have migrated to India from Pakistan", "description": "Notwithstanding anything in article 5, a person who has migrated to the territory of India from the territory now included in Pakistan shall be deemed to be a citizen of India if he or either of his parents or any of his grand-parents was born in India and has been ordinarily resident in the territory of India since the date of his migration.", "keywords": ["migration", "pakistan", "citizenship", "partition"], "category": "Citizenship"},
        {"number": "7", "title": "Rights of citizenship of certain migrants to Pakistan", "description": "Notwithstanding anything in articles 5 and 6, a person who has after the 1st day of March, 1947, migrated from the territory of India to the territory now included in Pakistan shall not be deemed to be a citizen of India.", "keywords": ["migration", "pakistan", "citizenship"], "category": "Citizenship"},
        {"number": "8", "title": "Rights of citizenship of certain persons of Indian origin residing outside India", "description": "Notwithstanding anything in article 5, any person who or either of whose parents or any of whose grand-parents was born in India as defined in the Government of India Act, 1935, and who is ordinarily residing in any country outside undivided India shall be deemed to be a citizen of India if he has been registered as a citizen of India.", "keywords": ["indian origin", "overseas", "citizenship", "NRI"], "category": "Citizenship"},
        {"number": "9", "title": "Persons voluntarily acquiring citizenship of a foreign State not to be citizens", "description": "No person shall be a citizen of India by virtue of article 5, or be deemed to be a citizen of India by virtue of article 6 or article 8, if he has voluntarily acquired the citizenship of any foreign State.", "keywords": ["foreign citizenship", "voluntary acquisition", "dual citizenship"], "category": "Citizenship"},
        {"number": "10", "title": "Continuance of the rights of citizenship", "description": "Every person who is or is deemed to be a citizen of India under any of the foregoing provisions of this Part shall, subject to the provisions of any law that may be made by Parliament, continue to be such citizen.", "keywords": ["continuance", "citizenship"], "category": "Citizenship"},
        {"number": "11", "title": "Parliament to regulate the right of citizenship by law", "description": "Nothing in the foregoing provisions of this Part shall derogate from the power of Parliament to make any provision with respect to the acquisition and termination of citizenship and all other matters relating to citizenship.", "keywords": ["parliament", "citizenship law", "regulation"], "category": "Citizenship"},
    ])
    
    # ==================== PART III: FUNDAMENTAL RIGHTS ====================
    data["articles"].extend([
        {"number": "12", "title": "Definition of State", "description": "In this part, unless the context otherwise requires, the State includes the Government and Parliament of India and the Government and the Legislature of each of the States and all local or other authorities within the territory of India or under the control of the Government of India.", "keywords": ["state", "definition", "government", "parliament", "legislature"], "category": "Fundamental Rights"},
        {"number": "13", "title": "Laws inconsistent with or in derogation of the fundamental rights", "description": "All laws in force in the territory of India immediately before the commencement of this Constitution, in so far as they are inconsistent with the provisions of this Part, shall, to the extent of such inconsistency, be void. The State shall not make any law which takes away or abridges the rights conferred by this Part and any law made in contravention of this clause shall, to the extent of the contravention, be void.", "keywords": ["laws", "fundamental rights", "void", "inconsistent", "judicial review"], "category": "Fundamental Rights"},
        {"number": "14", "title": "Equality before law", "description": "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.", "keywords": ["equality", "equal protection", "law", "discrimination"], "category": "Right to Equality"},
        {"number": "15", "title": "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth", "description": "The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, place of birth or any of them. No citizen shall, on grounds only of religion, race, caste, sex, place of birth or any of them, be subject to any disability, liability, restriction or condition with regard to access to shops, public restaurants, hotels and places of public entertainment.", "keywords": ["discrimination", "religion", "race", "caste", "sex", "equality", "public places"], "category": "Right to Equality"},
        {"number": "16", "title": "Equality of opportunity in matters of public employment", "description": "There shall be equality of opportunity for all citizens in matters relating to employment or appointment to any office under the State. No citizen shall, on grounds only of religion, race, caste, sex, descent, place of birth, residence or any of them, be ineligible for, or discriminated against in respect of, any employment or office under the State.", "keywords": ["employment", "public service", "equality", "opportunity", "reservation"], "category": "Right to Equality"},
        {"number": "17", "title": "Abolition of Untouchability", "description": "Untouchability is abolished and its practice in any form is forbidden. The enforcement of any disability arising out of Untouchability shall be an offence punishable in accordance with law.", "keywords": ["untouchability", "abolition", "social equality", "caste discrimination"], "category": "Right to Equality"},
        {"number": "18", "title": "Abolition of titles", "description": "No title, not being a military or academic distinction, shall be conferred by the State. No citizen of India shall accept any title from any foreign State. No person who is not a citizen of India shall, while he holds any office of profit or trust under the State, accept without the consent of the President any title from any foreign State.", "keywords": ["titles", "abolition", "awards", "foreign titles"], "category": "Right to Equality"},
        {"number": "19", "title": "Protection of certain rights regarding freedom of speech, etc.", "description": "All citizens shall have the right: (a) to freedom of speech and expression; (b) to assemble peaceably and without arms; (c) to form associations or unions or co-operative societies; (d) to move freely throughout the territory of India; (e) to reside and settle in any part of the territory of India; (f) to practice any profession, or to carry on any occupation, trade or business.", "keywords": ["freedom", "speech", "expression", "assembly", "association", "movement", "profession", "trade"], "category": "Right to Freedom"},
        {"number": "20", "title": "Protection in respect of conviction for offences", "description": "No person shall be convicted of any offence except for violation of a law in force at the time of the commission of the act charged as an offence, nor be subjected to a penalty greater than that which might have been inflicted under the law in force at the time of the commission of the offence. No person shall be prosecuted and punished for the same offence more than once. No person accused of any offence shall be compelled to be a witness against himself.", "keywords": ["conviction", "ex post facto", "double jeopardy", "self-incrimination", "criminal law"], "category": "Right to Freedom"},
        {"number": "21", "title": "Protection of life and personal liberty", "description": "No person shall be deprived of his life or personal liberty except according to procedure established by law.", "keywords": ["life", "liberty", "personal liberty", "procedure", "law", "fundamental right", "due process"], "category": "Right to Freedom"},
        {"number": "21A", "title": "Right to education", "description": "The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may, by law, determine.", "keywords": ["education", "children", "free education", "compulsory education", "right to education", "RTE"], "category": "Right to Education"},
        {"number": "22", "title": "Protection against arrest and detention in certain cases", "description": "No person who is arrested shall be detained in custody without being informed, as soon as may be, of the grounds for such arrest nor shall he be denied the right to consult, and to be defended by, a legal practitioner of his choice. Every person who is arrested and detained in custody shall be produced before the nearest magistrate within a period of twenty-four hours of such arrest excluding the time necessary for the journey from the place of arrest to the court of the magistrate.", "keywords": ["arrest", "detention", "custody", "legal practitioner", "magistrate", "habeas corpus", "24 hours"], "category": "Right to Freedom"},
        {"number": "23", "title": "Prohibition of traffic in human beings and forced labour", "description": "Traffic in human beings and begar and other similar forms of forced labour are prohibited and any contravention of this provision shall be an offence punishable in accordance with law. Nothing in this article shall prevent the State from imposing compulsory service for public purposes.", "keywords": ["human trafficking", "forced labour", "begar", "slavery", "bonded labour"], "category": "Right against Exploitation"},
        {"number": "24", "title": "Prohibition of employment of children in factories, etc.", "description": "No child below the age of fourteen years shall be employed to work in any factory or mine or engaged in any other hazardous employment.", "keywords": ["child labour", "children", "employment", "factory", "mine", "hazardous work"], "category": "Right against Exploitation"},
        {"number": "25", "title": "Freedom of conscience and free profession, practice and propagation of religion", "description": "Subject to public order, morality and health and to the other provisions of this Part, all persons are equally entitled to freedom of conscience and the right freely to profess, practice and propagate religion.", "keywords": ["religion", "conscience", "freedom", "propagation", "religious freedom"], "category": "Right to Freedom of Religion"},
        {"number": "26", "title": "Freedom to manage religious affairs", "description": "Subject to public order, morality and health, every religious denomination or any section thereof shall have the right: (a) to establish and maintain institutions for religious and charitable purposes; (b) to manage its own affairs in matters of religion; (c) to own and acquire movable and immovable property; and (d) to administer such property in accordance with law.", "keywords": ["religious affairs", "religious institutions", "property", "management", "denomination"], "category": "Right to Freedom of Religion"},
        {"number": "27", "title": "Freedom as to payment of taxes for promotion of any particular religion", "description": "No person shall be compelled to pay any taxes, the proceeds of which are specifically appropriated in payment of expenses for the promotion or maintenance of any particular religion or religious denomination.", "keywords": ["taxes", "religion", "freedom", "payment", "secular state"], "category": "Right to Freedom of Religion"},
        {"number": "28", "title": "Freedom as to attendance at religious instruction or religious worship in certain educational institutions", "description": "No religious instruction shall be provided in any educational institution wholly maintained out of State funds. No person attending any educational institution recognised by the State or receiving aid out of State funds shall be required to take part in any religious instruction that may be imparted in such institution or to attend any religious worship that may be conducted in such institution.", "keywords": ["religious instruction", "education", "worship", "freedom", "secular education"], "category": "Right to Freedom of Religion"},
        {"number": "29", "title": "Protection of interests of minorities", "description": "Any section of the citizens residing in the territory of India or any part thereof having a distinct language, script or culture of its own shall have the right to conserve the same. No citizen shall be denied admission into any educational institution maintained by the State or receiving aid out of State funds on grounds only of religion, race, caste, language or any of them.", "keywords": ["minorities", "language", "script", "culture", "protection", "cultural rights", "education"], "category": "Cultural and Educational Rights"},
        {"number": "30", "title": "Right of minorities to establish and administer educational institutions", "description": "All minorities, whether based on religion or language, shall have the right to establish and administer educational institutions of their choice. In making any law providing for the compulsory acquisition of any property of an educational institution established and administered by a minority, the State shall ensure that the amount fixed by or determined under such law for the acquisition of such property is such as would not restrict or abrogate the right guaranteed under this article.", "keywords": ["minorities", "educational institutions", "administration", "religious minorities", "linguistic minorities"], "category": "Cultural and Educational Rights"},
        {"number": "31", "title": "Compulsory acquisition of property (Repealed)", "description": "This article dealing with the right to property was repealed by the 44th Amendment Act, 1978. The right to property is now a legal right under Article 300A, not a fundamental right.", "keywords": ["property", "repealed", "acquisition", "44th amendment"], "category": "Right to Property (Repealed)"},
        {"number": "32", "title": "Remedies for enforcement of rights conferred by this Part", "description": "The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by this Part is guaranteed. The Supreme Court shall have power to issue directions or orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari, whichever may be appropriate, for the enforcement of any of the rights conferred by this Part.", "keywords": ["supreme court", "remedies", "enforcement", "fundamental rights", "writ", "habeas corpus", "mandamus", "certiorari", "prohibition", "quo warranto"], "category": "Right to Constitutional Remedies"},
        {"number": "33", "title": "Power of Parliament to modify the rights conferred by this Part in their application to Forces, etc.", "description": "Parliament may, by law, determine to what extent any of the rights conferred by this Part shall, in their application to the members of the Armed Forces or the Forces charged with the maintenance of public order, be restricted or abrogated so as to ensure the proper discharge of their duties and the maintenance of discipline among them.", "keywords": ["armed forces", "modification", "parliament", "discipline", "military"], "category": "Fundamental Rights"},
        {"number": "34", "title": "Restriction on rights conferred by this Part while martial law is in force in any area", "description": "Notwithstanding anything in the foregoing provisions of this Part, Parliament may by law indemnify any person in the service of the Union or of a State or any other person in respect of any act done by him in connection with the maintenance or restoration of order in any area within the territory of India where martial law was in force.", "keywords": ["martial law", "restriction", "indemnity", "emergency"], "category": "Fundamental Rights"},
        {"number": "35", "title": "Legislation to give effect to the provisions of this Part", "description": "Notwithstanding anything in this Constitution, Parliament shall have, and the Legislature of a State shall not have, power to make laws with respect to any of the matters which under clause (3) of article 16, clause (3) of article 32, article 33 and article 34 may be provided for by law made by Parliament.", "keywords": ["legislation", "parliament", "implementation", "fundamental rights"], "category": "Fundamental Rights"},
    ])
    
    # ==================== PART IV: DIRECTIVE PRINCIPLES ====================
    data["articles"].extend([
        {"number": "36", "title": "Definition of State", "description": "In this Part, unless the context otherwise requires, the State has the same meaning as in Part III.", "keywords": ["state", "definition", "directive principles"], "category": "Directive Principles"},
        {"number": "37", "title": "Application of the principles contained in this Part", "description": "The provisions contained in this Part shall not be enforceable by any court, but the principles therein laid down are nevertheless fundamental in the governance of the country and it shall be the duty of the State to apply these principles in making laws.", "keywords": ["non-justiciable", "fundamental", "governance", "principles", "non-enforceable"], "category": "Directive Principles"},
        {"number": "38", "title": "State to secure a social order for the promotion of welfare of the people", "description": "The State shall strive to promote the welfare of the people by securing and protecting as effectively as it may a social order in which justice, social, economic and political, shall inform all the institutions of the national life. The State shall, in particular, strive to minimise the inequalities in income, and endeavour to eliminate inequalities in status, facilities and opportunities.", "keywords": ["social order", "welfare", "justice", "social justice", "economic justice", "political justice", "inequality"], "category": "Directive Principles"},
        {"number": "39", "title": "Certain principles of policy to be followed by the State", "description": "The State shall, in particular, direct its policy towards securing: (a) that the citizens, men and women equally, have the right to an adequate means of livelihood; (b) that the ownership and control of the material resources of the community are so distributed as best to subserve the common good; (c) that the operation of the economic system does not result in the concentration of wealth and means of production to the common detriment; (d) that there is equal pay for equal work for both men and women; (e) that the health and strength of workers, men and women, and the tender age of children are not abused; (f) that children are given opportunities to develop in a healthy manner.", "keywords": ["policy", "livelihood", "resources", "wealth distribution", "economic system", "common good", "equal pay"], "category": "Directive Principles"},
        {"number": "39A", "title": "Equal justice and free legal aid", "description": "The State shall secure that the operation of the legal system promotes justice, on a basis of equal opportunity, and shall, in particular, provide free legal aid, by suitable legislation or schemes or in any other way, to ensure that opportunities for securing justice are not denied to any citizen by reason of economic or other disabilities.", "keywords": ["equal justice", "free legal aid", "access to justice", "legal system", "legal services"], "category": "Directive Principles"},
        {"number": "40", "title": "Organisation of village panchayats", "description": "The State shall take steps to organise village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.", "keywords": ["panchayat", "village", "local government", "self-government", "rural"], "category": "Directive Principles"},
        {"number": "41", "title": "Right to work, to education and to public assistance in certain cases", "description": "The State shall, within the limits of its economic capacity and development, make effective provision for securing the right to work, to education and to public assistance in cases of unemployment, old age, sickness and disablement, and in other cases of undeserved want.", "keywords": ["work", "education", "public assistance", "unemployment", "old age", "social security"], "category": "Directive Principles"},
        {"number": "42", "title": "Provision for just and humane conditions of work and maternity relief", "description": "The State shall make provision for securing just and humane conditions of work and for maternity relief.", "keywords": ["working conditions", "maternity relief", "humane conditions", "labour welfare", "maternity benefits"], "category": "Directive Principles"},
        {"number": "43", "title": "Living wage, etc., for workers", "description": "The State shall endeavour to secure, by suitable legislation or economic organisation or in any other way, to all workers, agricultural, industrial or otherwise, work, a living wage, conditions of work ensuring a decent standard of life and full enjoyment of leisure and social and cultural opportunities.", "keywords": ["living wage", "workers", "decent standard", "leisure", "labour rights"], "category": "Directive Principles"},
        {"number": "43A", "title": "Participation of workers in management of industries", "description": "The State shall take steps, by suitable legislation or in any other way, to secure the participation of workers in the management of undertakings, establishments or other organisations engaged in any industry.", "keywords": ["workers participation", "management", "industries", "co-determination", "industrial democracy"], "category": "Directive Principles"},
        {"number": "43B", "title": "Promotion of co-operative societies", "description": "The State shall endeavour to promote voluntary formation, autonomous functioning, democratic control and professional management of co-operative societies.", "keywords": ["cooperative societies", "promotion", "voluntary", "democratic", "co-operatives"], "category": "Directive Principles"},
        {"number": "44", "title": "Uniform civil code for the citizens", "description": "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.", "keywords": ["uniform civil code", "UCC", "civil code", "citizens", "directive principles", "personal law"], "category": "Directive Principles"},
        {"number": "45", "title": "Provision for early childhood care and education to children below the age of six years", "description": "The State shall endeavour to provide early childhood care and education for all children until they complete the age of six years.", "keywords": ["early childhood", "education", "children", "care", "pre-primary", "ECCE"], "category": "Directive Principles"},
        {"number": "46", "title": "Promotion of educational and economic interests of Scheduled Castes, Scheduled Tribes and other weaker sections", "description": "The State shall promote with special care the educational and economic interests of the weaker sections of the people, and, in particular, of the Scheduled Castes and the Scheduled Tribes, and shall protect them from social injustice and all forms of exploitation.", "keywords": ["scheduled castes", "scheduled tribes", "weaker sections", "education", "economic interests", "social justice", "SC", "ST"], "category": "Directive Principles"},
        {"number": "47", "title": "Duty of the State to raise the level of nutrition and the standard of living and to improve public health", "description": "The State shall regard the raising of the level of nutrition and the standard of living of its people and the improvement of public health as among its primary duties and, in particular, the State shall endeavour to bring about prohibition of the consumption except for medicinal purposes of intoxicating drinks and of drugs which are injurious to health.", "keywords": ["nutrition", "standard of living", "public health", "prohibition", "health policy"], "category": "Directive Principles"},
        {"number": "48", "title": "Organisation of agriculture and animal husbandry", "description": "The State shall endeavour to organise agriculture and animal husbandry on modern and scientific lines and shall, in particular, take steps for preserving and improving the breeds, and prohibiting the slaughter, of cows and calves and other milch and draught cattle.", "keywords": ["agriculture", "animal husbandry", "cattle", "cow protection", "scientific farming"], "category": "Directive Principles"},
        {"number": "48A", "title": "Protection and improvement of environment and safeguarding of forests and wild life", "description": "The State shall endeavour to protect and improve the environment and to safeguard the forests and wild life of the country.", "keywords": ["environment", "forests", "wildlife", "protection", "ecology", "conservation"], "category": "Directive Principles"},
        {"number": "49", "title": "Protection of monuments and places and objects of national importance", "description": "It shall be the obligation of the State to protect every monument or place or object of artistic or historic interest, declared by or under law made by Parliament to be of national importance, from spoliation, disfigurement, destruction, removal, disposal or export, as the case may be.", "keywords": ["monuments", "heritage", "protection", "national importance", "cultural property", "ASI"], "category": "Directive Principles"},
        {"number": "50", "title": "Separation of judiciary from executive", "description": "The State shall take steps to separate the judiciary from the executive in the public services of the State.", "keywords": ["separation of powers", "judiciary", "executive", "independence", "judicial independence"], "category": "Directive Principles"},
        {"number": "51", "title": "Promotion of international peace and security", "description": "The State shall endeavour to: (a) promote international peace and security; (b) maintain just and honourable relations between nations; (c) foster respect for international law and treaty obligations in the dealings of organised peoples with one another; and (d) encourage settlement of international disputes by arbitration.", "keywords": ["international peace", "security", "foreign policy", "international law", "arbitration", "diplomacy"], "category": "Directive Principles"},
    ])
    
    # ==================== PART IVA: FUNDAMENTAL DUTIES ====================
    data["articles"].extend([
        {"number": "51A", "title": "Fundamental Duties", "description": "It shall be the duty of every citizen of India: (a) to abide by the Constitution and respect its ideals and institutions, the National Flag and the National Anthem; (b) to cherish and follow the noble ideals which inspired our national struggle for freedom; (c) to uphold and protect the sovereignty, unity and integrity of India; (d) to defend the country and render national service when called upon to do so; (e) to promote harmony and the spirit of common brotherhood amongst all the people of India transcending religious, linguistic and regional or sectional diversities; to renounce practices derogatory to the dignity of women; (f) to value and preserve the rich heritage of our composite culture; (g) to protect and improve the natural environment including forests, lakes, rivers and wild life, and to have compassion for living creatures; (h) to develop the scientific temper, humanism and the spirit of inquiry and reform; (i) to safeguard public property and to abjure violence; (j) to strive towards excellence in all spheres of individual and collective activity so that the nation constantly rises to higher levels of endeavour and achievement; (k) who is a parent or guardian to provide opportunities for education to his child or, as the case may be, ward between the age of six and fourteen years.", "keywords": ["fundamental duties", "duties", "citizen", "constitution", "national flag", "national anthem", "sovereignty", "unity", "integrity", "environment", "scientific temper"], "category": "Fundamental Duties"},
    ])
    
    print(f"Generated {len(data['articles'])} articles so far...")
    
    return data

# Run the generator
if __name__ == "__main__":
    print("Generating comprehensive constitution database...")
    print("This includes 150+ articles, procedures, and landmark cases...")
    
    data = create_comprehensive_database()
    
    # Save to file
    output_path = os.path.join('data', 'constitution_data.json')
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[SUCCESS] Generated {len(data['articles'])} articles")
    print(f"[SUCCESS] Saved to: {output_path}")
    print("\nDatabase is ready to use!")

